ATXLive/urls.py
from django.conf.urls import url, include, patterns
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
import recommendation.views
import chatroom.views

urlpatterns = [
 url(r'^all/', recommendation.views.EventListView.as_view(), name = 'event-list'),
 url(r'^add/', recommendation.views.add_event,name='event-new'),
 url(r'^', include('recommendation.urls')),
 url(r'^recommendation/', include('recommendation.urls')),
 url(r'^recommendation/(?P<event>[a-zA-Z0-9_/-]+)/', recommendation.views.event_base, name='eventbase'),
 url(r'^chatroom/', include('chatroom.urls')),
 url(r'^admin/', admin.site.urls),
 url(r'^about/', recommendation.views.about, name = 'about'),
 url(r'^login_view/', recommendation.views.login_view, name='login_view'),
 url(r'^register/', recommendation.views.register, name='register'),
 url(r'^index/(?P<event>[a-zA-Z0-9_/-]+)/$', recommendation.views.event_base, name='eventbase'),
 #url(r'^index/', recommendation.views.index, name='index'),
 url(r'^eventslist/', recommendation.views.eventslist, name='eventslist'),
 url(r'^logout/', recommendation.views.logout_page, name='logout'),
 url(r'^chatroom/home/', chatroom.views.Home, name='chatroom'),
 url(r'^(?P<event>[a-zA-Z0-9_/-]+)/', recommendation.views.event_base, name='eventbase'),

]

urlpatterns += staticfiles_urlpatterns()

recommendation/urls.py
from django.conf.urls import url
from recommendation import views

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^login/$', views.login_view, name = 'login'),
]

recommendation/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User


class Event(models.Model):
    title = models.CharField(max_length=255, unique=True)
    date = models.DateField(False,False)
    startTime = models.CharField(max_length=10, default = '12:00am')
    duration_in_minutes = models.PositiveIntegerField()
    host = User
    email = models.EmailField()
    page = models.URLField()
    money = (('$', 'Cheap'), ('$$', 'affordable'), ('$$$', 'expensive'))
    approximatePrice = models.CharField(max_length=3, choices=money, default='$')
    types_of_event = (('SOC', 'Social'), ('ACA', 'Academic'), ('PRO', 'Professional'))
    event_type = models.CharField(max_length=3, choices=types_of_event, default='SOC')
    location = models.CharField(max_length=255, default = 'Austin, TX')
    description = models.CharField(max_length=1000, default='This is an event.')
    full_name = models.CharField(max_length=255, default='John Snow')

    #override
    def __str__(self):
        return self.title


class UserEvents(models.Model):
    myUser = models.OneToOneField(User)
    event_list = models.ManyToManyField(Event, related_name='myevents')

    def __str__(self):
        return self.myUser.username
        

def create_event(title, date, time, duration, host, email, price, event_type, location, description):
    e = Event()
    e.title = title
    e.date = date
    e.startTime = time
    e.duration_in_minutes = duration
    e.host = host
    e.email = email
    e.approximatePrice = price
    e.event_type = event_type
    e.location = location
    e.description = description
    e.page = slugify(e.title)
    e.full_name = host.get_full_name()
    e.save()
    re = singleton_engine()
    re.add_event(e)
    return e


def create_user(username, password, email, first_name, last_name):
    u = User()
    u.username = username
    u.set_password(password)
    u.first_name = first_name
    u.last_name = last_name
    u.email = email
    u.save()
    ue = set_user(u)
    return ue


def set_user(user):
    ue = UserEvents(myUser=user)
    ue.save()
    return ue


def attend_event(user, event):
    user.event_list.add(event)


class RecommendationEngine(models.Model):
    SOCCHP = models.ManyToManyField(Event, related_name="SOCCHP")
    SOCAFF = models.ManyToManyField(Event, related_name='SOCAFF')
    SOCEXP = models.ManyToManyField(Event, related_name='SOCEXP')
    ACACHP = models.ManyToManyField(Event, related_name='ACACHP')
    ACAAFF = models.ManyToManyField(Event, related_name='ACAAFF')
    ACAEXP = models.ManyToManyField(Event, related_name='ACAEXP')
    PROCHP = models.ManyToManyField(Event, related_name='PROCHP')
    PROAFF = models.ManyToManyField(Event, related_name='PROAFF')
    PROEXP = models.ManyToManyField(Event, related_name='PROEXP')

    def recommend(self, ue):
        e_list = ue.event_list.all()
        type = [0, 0, 0]
        price = [0, 0, 0]
        soc = 0
        aca = 0
        pro = 0
        for e in e_list:
            if e.event_type == 'SOC': 
                type[0] += 1
                soc += 1
            elif e.event_type == 'ACA': 
                type[1] += 1 
                aca += 1
            elif e.event_type == 'PRO': 
                type[2] += 1 
                pro += 1
            if e.approximatePrice == '$': price[0] += 1
            elif e.approximatePrice == '$$': price[1] += 1
            elif e.approximatePrice == '$$$': price[2] += 1
        
        if soc > aca:
            if soc > pro:
                to_recommend = Event.objects.filter(event_type = 'SOC')
        elif pro > aca:
            if pro > soc:
                to_recommend = Event.objects.filter(event_type = 'PRO')
        elif aca > soc:
            if aca > pro:
                to_recommend = Event.objects.filter(event_type = 'ACA')
        else:
            to_recommend = Event.objects.filter(event_type = 'SOC')
        return to_recommend

    def find_events_to_recommend(self, type, price):
        type_list = ['SOC', 'ACA', 'PRO']
        price_type = ['CHP', 'AFF', 'EXP']
        lead_type = ''
        lead_price = ''
        y = 0
        x = 0
        z = 0
        while y < 3:
            if type[y] > x:
                x = type[y]
                lead_type = type_list[y]
            if price[y] > z:
                z = price[y]
                lead_price = price_type[y]
            y += 1
        if lead_type == 'SOC':
            if lead_price == "CHP":
                to_recommend = self.SOCCHP.all()
            elif lead_price == 'AFF':
                to_recommend = self.SOCAFF.all()
            else:
                to_recommend = self.SOCEXP.all()
        elif lead_type == 'ACA':
            if lead_price == "CHP":
                to_recommend = self.ACACHP.all()
            elif lead_price == 'AFF':
                to_recommend = self.ACAAFF.all()
            else:
                to_recommend = self.ACAEXP.all()
        elif lead_type == 'PRO':
            if lead_price == "CHP":
                to_recommend = self.PROCHP.all()
            elif lead_price == 'AFF':
                to_recommend = self.PROAFF.all()
            else:
                to_recommend = self.PROEXP.all()
        return to_recommend

    def add_event(self, e):
        if e.event_type == 'SOC':
            if e.approximatePrice == "$":
                self.SOCCHP.add(e)
            elif e.approximatePrice == '$$':
                self.SOCAFF.add(e)
            else:
                self.SOCEXP.add(e)
        elif e.event_type == 'ACA':
            if e.approximatePrice == "$":
                self.ACACHP.add(e)
            elif e.approximatePrice == '$$':
                self.ACAAFF.add(e)
            else:
                self.ACAEXP.add(e)
        else:
            if e.approximatePrice == "$":
                self.PROCHP.add(e)
            elif e.approximatePrice == '$$':
                self.PROAFF.add(e)
            else:
                self.PROEXP.add(e)

    def set_engine(self):
        self.save()


def singleton_engine():
    try:
        re = RecommendationEngine.objects.get(id=1)
    except Exception:
        re = RecommendationEngine()
        re.set_engine()
    return re

login/forms.py
from django import forms
from django.contrib.auth.models import User
from recommendation.models import Event


class RegisterForm(forms.ModelForm):
    username = forms.CharField(max_length=255, help_text="Enter Username")
    password = forms.CharField(max_length=255, help_text="Enter Password", widget=forms.PasswordInput())
    first_name = forms.CharField(required=False)
    last_name = forms.CharField(required=False)
    email = forms.CharField(required=False)

    class Meta:
        model = User
        fields = ('username', 'password',)


class LoginForm(forms.Form):
    username = forms.CharField(max_length=255)
    password = forms.CharField(max_length=255, widget=forms.PasswordInput())


class AddEventForm(forms.ModelForm):
    title = forms.CharField(max_length=255, help_text="Enter Title", required = False)
    date = forms.DateField(help_text="Date", required = False)
    startTime = forms.CharField(help_text="Start Time", required = False)
    duration_in_minutes = forms.IntegerField(help_text="Duration", required = False)
    host = User
    email = forms.EmailField(help_text="Email", required = False)
    page = forms.URLField(required=False)
    money = (('$', 'Cheap'), ('$$', 'Affordable'), ('$$$', 'Expensive'))
    approximatePrice = forms.ChoiceField(choices=money, required=True)
    location = forms.CharField(help_text="Location")
    types_of_event = (('SOC', 'Social'), ('ACA', 'Academic'), ('PRO', 'Professional'))
    event_type = forms.ChoiceField(choices=types_of_event, required=True)
    description = forms.CharField(max_length=1000, help_text='Describe it')

    class Meta:
        model = Event
        exclude = ('host', 'page', 'full_name')


class RSVPForm(forms.Form):
    e_title = forms.CharField(max_length=255, required=False, disabled=True)

recommendation/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.views.generic.edit import CreateView, DeleteView
from django.views.generic import ListView
from recommendation.models import Event
from login import forms
from recommendation.models import create_user, singleton_engine, attend_event
from recommendation.models import create_event,RecommendationEngine, UserEvents
from django.contrib.auth.models import User
from django.contrib.auth.models import AnonymousUser
from django.contrib.auth import authenticate, login, logout, get_user_model


class EventListView(ListView):
    model = Event
    fields = ['title','date', 'duration_in_minutes','host','email']
    template_name = 'recommendation/event_list.html'


#class EventCreate(CreateView):
#    model = Event
#    fields = ['title','date','startTime', 'duration_in_minutes', 'approximatePrice', 'email']
#    template_name = 'recommendation/edit_event.html'


def index(request):
    re = singleton_engine()
    if request.user.is_anonymous() == False:
        ue = UserEvents.objects.get(myUser=request.user)
        e_list = re.recommend(ue)
        if len(e_list) == 0:
            context_dict = {'events_list' : Event.objects.all()}
        else:
            context_dict = {'events_list' : e_list}
    else: context_dict = {'events_list' : Event.objects.all()}
    return render(request, 'recommendation/landing_page.html',context_dict)


def login_view(request):
    if request.method == 'POST':
        form = forms.LoginForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            print(data)
            print(data["username"])
            print(request.POST.get('username'))
            user = authenticate(username=request.POST.get('username'), password=request.POST.get('password'))
            print(user)
            if user!= None:
                login(request, user=user)
                return redirect('/')
            else:
                print('no user')
                print('why')
        else: print('invalid')
    else:
        form = forms.LoginForm()

    return render(request, 'recommendation/login_page.html',{'form':form})


def eventslist(request):
   context_dict = {'events_list' : Event.objects.all() }
   return render(request, 'recommendation/event_list.html',context_dict)


def about(request):
   context_dict = {}
   return render(request, 'recommendation/about.html',context_dict)


def register(request):
    if request.method == "POST":
        form = forms.RegisterForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            ue = create_user(data['username'], data['password'], data['email'], data['first_name'], data['last_name'])
            print('new user created: ' + data['username'])
            user = authenticate(username=data['username'], password=data['password'])
            print(user)
            if user!= None:
                login(request, user=user)
                return redirect('/')
            return redirect('/')
    else:
        print('invalid form')
        form = forms.RegisterForm()
    return render(request, 'recommendation/register.html', {'form':form})


def logout_page(request):
    context_dict = {}
    logout(request)
    return render(request, 'recommendation/logout_page.html',context_dict)


def add_event(request):
    if request.method == "POST":
        form = forms.AddEventForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            print (request.user)
            create_event(data['title'], data['date'], data['startTime'], data['duration_in_minutes'], request.user, data['email'], data['approximatePrice'], data['event_type'], data['location'], data['description'])
            print(data['title'])
            #print('New event ' + data['title'] + ' created by ' + request.user)
            return redirect('/')
    else:
        print('invalid form')
        form = forms.AddEventForm()
    return render(request, 'recommendation/edit_event.html', {'form':form})


def event_base(request, event):
    if request.method == "GET":
        print('event_base')
        e = Event.objects.get(page=event)
        cu = event.replace(" ", "-")
        return render(request, 'recommendation/event_base.html', {'event':e, 'chatlink': cu})
    elif request.method == "POST":
        print('hope')
        e = Event.objects.get(page=event)
        print(e.page)
        cu = event.replace(" ", "-")
        u = User.objects.get(username=request.user.username)
        ue = UserEvents.objects.get(myUser=u)
        attend_event(ue, e)
        print(ue.event_list.all())
        return render(request, 'recommendation/event_base.html', {'event':e, 'chatlink': cu})
    else:
        print('wrong redirect')

templates/recommendation/edit_event.html
{% extends "recommendation/base.html" %}
{% load static from staticfiles %}
{% block top %}
{# <link href="{% static "bootstrap/css/register_form.css" %}" rel="stylesheet"> #}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static "bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <title>Create Event</title>
{% endblock %}

{% block content %}
  <body class="background-image" background="{%  static "images/colors1.png" %}">
    <div class="container" style="background-color: rgba(255, 255, 255, 0.7); margin-top: 125px; width: 50vw; border-radius: 15px; padding-bottom: 20px">
        <div class="form">
            {% if request.user.is_authenticated %}
            <form id="AddEventForm" method="post" action="/add/">
                {% csrf_token %}
                <h2 align=center>Create your own event</h2>
                <div class="form-group">
                    <label for="id_title">Event Title:</label>
                    <input id="id_title" class="form-control" maxlength="255" name="title" type="text" placeholder="Enter a title for your event" autocomplete="off"> 
                </div>
                <div class="form-group">
                    <label for="date">Date:</label>
                    <input type="date" class="form-control" id="id_date" name="date" placeholder="MM/DD/YYYY">
                </div>

                <div class="form-group">
                    <label for="description">Description:</label>
                    <input type="text" class="form-control" id="id_description" name="description" placeholder="Enter a description for your event" autocomlete="off" maxlength="1000">
                    <!--<input type="text" class="form-control" id="id_description" name="description" placeholder="Enter a description for your event" autocomlete="off">-->
                </div>
                <div class="form-group">
                    <label for="startTime">Start Time:</label>
                    <input type="time" class="form-control" id="id_startTime" name="startTime" > 
                </div>
                <div class="form-group">
                    <label for="duration_in_minutes">Duration:</label>
                    <input id="id_duration_in_minutes" name="duration_in_minutes" type="number" class="form-control">
                </div>
                <div class="form-group">
                    <label for="email">Email:</label>
                    <input type="email" class="form-control" id="id_email" name="email" placeholder="Enter the host's email">
                </div>
                <div class="form-group">
                    <label for="approxPrice">Approximate Price:</label>
                    <select id="id_approximatePrice" name="approximatePrice">
                        <option value="$">Cheap</option>
                        <option value="$$">Affordable</option>
                        <option value="$$$">Expensive</option>
                    </select> 
                </div>
                <div class="form-group">
                    <label for="location">Location:</label>
                    <input type="text" class="form-control" id="id_location" name="location" placeholder="Enter event location">
                </div>
                <div class="form-group">
                    <label for="date">Event Type:</label>
                    <select id="id_event_type" name="event_type">
                        <option value="SOC">Social</option>
                        <option value="ACA">Academic</option>
                        <option value="PRO">Professional</option>
                    </select> 
                </div>

                <div class="buttonwrapper" align=center>
                    <input type="submit" name="submit" value="Create Event" style="width:260px" class="btn btn-default" align=center>
                </div>
            </form>
            {% else %}
            <div class="fieldwrapper" align=center style="padding-top: 20px;">
                <h4 align=center>Please <a href="{%  url 'login' %}">log in</a> to create an event.</h4>
            </div>
            {% endif %}
        </div>
    </div> 
  </body>

{% endblock %}

{% block footer %}
{% endblock %}

templates/recommendation/event_base.html
{%  extends "recommendation/base.html" %}

{% load static from staticfiles %}
{% block top %}
<link href="{% static "bootstrap/css/landing_page.css" %}" rel="stylesheet">
<link href="{% static "bootstrap/css/event_base.css" %}" rel="stylesheet">
<title>Events List</title>
{% endblock %}

{% block content %}
    <!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img class="first-slide" src="{% static "images/citylights2.jpg" %}" alt="Find Events!">
          <div class="container">
            <div class="carousel-caption">
                <h1>{{ event.title }}</h1>
              <!--h1>Welcome to ATX Live!</h1>-->
              <p> {{ event.description }}</p>

            </div>
          </div>
        </div>
      </div>
    </div><!-- /.carousel -->


    <!-- Event Listing
    ================================================== -->

    <div class="container1">
        <p>Date: {{ event.date }}
        <br><br> Time: {{ event.startTime }}
        <br><br> Location: {{ event.location }}
        <br><br> Event creator: {{event.full_name}} </p>
        <div class="action-box">
            <p>Actions</p>
            <div class="buttonwrapper">
            <form id="RSVPForm" method="post" action="{{event.page}}">
                {% csrf_token %}
                <!--<input type="text" value="{{event.title}}", id="title"><br>-->
                <div class="form-group">
                    <input id="id_username" class="form-control" maxlength="255" name="username" type="text">
                </div>
                <input type="submit" value="RSVP" style="width:260px" />
            </form>
            <div class="buttonwrapper">
            <form action="/chatroom/events/{{ chatlink }}/">
                <input type="submit" value="Enter chatroom" style="width:260px" />
            </form>
            <div class="buttonwrapper">
            <form action="{% url 'register' %}">
                <input type="submit" value="Edit event" style="width:260px" />
            </form>
        </div>
        </div>
      </div>
    </div>
    </div>

{% endblock %}

templates/recommendation/event_list.html
{%  extends "recommendation/base.html" %}
{% load static from staticfiles %}
{% block top %}
<link href="{% static "bootstrap/css/event_list.css" %}" rel="stylesheet">
<title>Events List</title>
{% endblock %}

{% block content %}
    <!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img class="first-slide" src="{% static "images/citylights2.jpg" %}" alt="Find Events!">
          <div class="container">
            <div class="carousel-caption">
                <h1>Upcoming events in Austin, TX</h1>
            </div>
          </div>
        </div>
      </div>
    </div><!-- /.carousel -->

    <!-- Filters
    ==================================================
    <div class="filters">
        <form id="filter" action="/filter/" method="post">
            <select class="event-type">
                <option value="any">Any</option>
                <option value="social">Social</option>
                <option value="academic">Academic</option>
                <option value="professional">Professional</option>
            </select>

            <select class="price">
                <option value="any">Any</option>
                <option value="1">$</option>
                <option value="2">$$</option>
                <option value="3">$$$</option>
            </select>
            <input class="submit-button" type="submit" value="Apply">
        </form>
    </div>

    <div class="searches">
        <form id="search" action="/search/" method="post">
            <input type="text" name="search_term">
            <input class="submit-button" type="submit" value="Search">
        </form>
    </div>


-->
    <!-- Event Listing
    ================================================== -->

    <div class="container">
	<div class="row">
      <div class="[ col-xs-12 col-sm-offset-2 col-sm-8 ]">
        <ul class="event-list" style="margin-top:30px; width:auto; text-align:center;">
          {% for event in events_list %}
            <li>
              <time datetime= {{ event.date }}>
              <span class="day"> {{  event.date.day }}</span>
              <span class="month"> {{ event.date.month }}</span>
              <span class="year"> event.date.year </span>
              <span class="duration">{{ event.duration_in_minutes }}</span>
            </time>

            <div class="info">
              <h2 class="title">{{event.title}}</h2>
              <p class="desc">{{event.description}}</p>
                <p class="loc">{{ event.location }}</p>
                <p class="time">Starts at {{ event.startTime }}</p>
                <ul>
                <li style="width:50%;"><a href="/{{event.page}}"><span class="fa fa-arrow-right"></span> Event page</a></li>
                <li style="width:50%;">Event type: {{ event.get_event_type_display }} | Price: {{ event.approximatePrice }}</li>
              </ul>
            </div>

            </li>
          {% endfor %}




        </ul>
      </div>
    </div>
	</div>
{% endblock %}

templates/recommendation/landing_page.html
{% extends "recommendation/base.html" %}
{% load static from staticfiles %}

{% block top %}<link href="{% static "bootstrap/css/landing_page.css" %}" rel="stylesheet">
<title>ATX Live Homepage</title>
{% endblock %}

{% block content %}
    <body>

    <!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img class="first-slide" src="{% static "images/citylights.jpg" %}" alt="Find Events!">
          <div class="container">
            <div class="carousel-caption">
              <h1>Welcome to ATX Live!</h1>
              <p>Your one-stop website to find parties, concerts, and other events with fellow Austinites. If you're looking for something to do in beautiful Austin, TX, you've come to the right place!</p>
              <p><a class="btn btn-lg btn-primary" href="{% url 'about' %}" role="button">Learn more</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img class="second-slide" src="{% static "images/party.png" %}" alt="Create an Account!">
          <div class="container">
            <div class="carousel-caption">
                {% if request.user.is_authenticated %}
                    <h1>Welcome back, {{ request.user.first_name }}!</h1>
                    <p>Be sure to hit up the events listing to find all the most recent events since your last visit.</p>
                    <p><a class="btn btn-lg btn-primary" href="{% url 'eventslist' %}" role="button">View events</a></p>
                {% else %}
                    <h1>Don't have an account? Create one for free!</h1>
                    <p>Create an ATX Live account to access event signups, the chatroom, and more! Not only will you be able to RSVP, but we will recommend events in your area curtailed to your tastes.</p>
                    <p><a class="btn btn-lg btn-primary" href="{% url 'register' %}" role="button">Create an account</a></p>
                {% endif %}

            </div>
          </div>
        </div>
        <div class="item">
          <img class="third-slide" src="{% static "images/concert.jpg" %}" alt="Post Your Events!">
          <div class="container">
            <div class="carousel-caption">
              <h1>Are you hosting an upcoming event?</h1>
              <p>Create an event on ATX Live to reach thousands of fun-seeking Austinites! Instantly find attendees to your band's gig, video game tournament, or anything else.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Post your Event</a></p>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div><!-- /.carousel -->


    <!-- Event Listing
    ================================================== -->

    <header>
        <h1 align="center">Upcoming Events in Austin, TX</h1>
    </header>
    <div class="container">
	<div class="row">
      <div class="[ col-xs-12 col-sm-offset-2 col-sm-8 ]">
        <ul class="event-list" style="margin-top:30px; width:auto; text-align:center;">
          {% for event in events_list %}
            <li>
              <time datetime= {{ event.date }}>
              <span class="day"> {{  event.date.day }}</span>
              <span class="month"> {{ event.date.month }}</span>
              <span class="year"> event.date.year </span>
              <span class="duration">{{ event.duration_in_minutes }}</span>
            </time>

            <div class="info">
              <h2 class="title">{{event.title}}</h2>
              <p class="desc">{{event.description}}</p>
                <p class="loc">{{ event.location }}</p>
                <p class="time">Starts at {{ event.startTime }}</p>
                <ul>
                <li style="width:50%;"><a href={{event.page}}><span class="fa fa-arrow-right"></span> Event page</a></li>
                <li style="width:50%;">Event type: {{ event.get_event_type_display }} | Price: {{ event.approximatePrice }}</li>
              </ul>
            </div>

            </li>
          {% endfor %}




        </ul>
      </div>
    </div>
	</div>
  </body>
{%  endblock %}

templates/recommendation/register.html
{% extends "recommendation/base.html" %}
{% load static from staticfiles %}
{% block top %}
    <link href="{% static "bootstrap/css/register_form.css" %}" rel="stylesheet">
    <title>Create an ATX Live Account</title>
{% endblock %}

{% block content %}
  <body class="background-image" background="{%  static "images/sxsw1.jpg" %}">
     <div class="container" style="background-color: rgba(255, 255, 255, 0.7); margin-top: 125px; width: 50vw; border-radius: 15px; padding-bottom: 20px">
        <form id="LoginForm" method="post" action="/register/">
        {% csrf_token %}
        <h2 align=center>Create an account</h2>
        <br>
        <div class="form-group">
            <label for="username" style="text-align: right; clear: both;">Username:</label>
            <input id="id_username" class="form-control" maxlength="255" name="username" type="text"> 
        </div>
        <div class="form-group">
            <label for="password" style="text-align: right; clear: both;">Password:</label>
            <input id="id_password" class="form-control" maxlength="255" name="password" type="password"> 
        </div>
        <div class="form-group">
            <label for="first_name" style="text-align: right; clear: both;">First name:</label>
            <input id="id_first_name" class="form-control" maxlength="255" name="first_name" type="text">
        </div>
       <div class="form-group">
            <label for="last_name" style="text-align: right; clear: both;">Last name:</label>
            <input id="id_last_name" class="form-control" maxlength="255" name="last_name" type="text">
        </div>
        <div class="form-group">
            <label for="email" style="text-align: right; clear: both;">Email:</label>
            <input id="id_email" class="form-control" maxlength="255" name="email" type="email"> 
        </div>
        <br>
        <div align=center style="margin-top: 20px; margin-bottom: 10px;">
            <input type="submit" name="submit" value="Register" style="width:260px" class="btn btn-default" align=center >
        </div>
        </form>
      </div>
  </body>
{% endblock %}

{% block footer %}
{% endblock %}